 export const playlist=[
    {
        id:1,
        Singer:"Eldar Mansurov & Briliant Dadaşova",
        Music:"Bayatılar",
        MusicPath:"Eldar Mansurov  Bayatılar (İfa_ Brilliant Dadaşova)  1989.mp3",
        ImagePath:"Eldar Mansurov.jpg",
        Time:351,
},
    {
        id:2,
        Singer:"Eyyub Yaqubov",
        Music:"Yağış",
        MusicPath:"Eyyub Yaqubov  Yağış (Rəsmi Musiqi Videosu).mp3",
        ImagePath:"Eyyub Yaqubov.jpg",
        Time:322,
},
    {
        id:3,
        Singer:"The Weeknd",
        Music:"Call Out of My Name",
        MusicPath:"The Weeknd - Call Out My Name (Official Audio).mp3",
        ImagePath:"The Weeknd.jpg",
        Time:228,
},
    {
        id:4,
        Singer:"Şebnem Ferah",
        Music:"Yağmurlar",
        MusicPath:"Sebnem Ferah - Yagmurlar.mp3",
        ImagePath:"Sebnem Ferah.jpg",
        Time:291,
},
    {
        id:5,
        Singer:"Röya",
        Music:"Bahar",
        MusicPath:"Röya - Bahar.mp3",
        ImagePath:"Röya.webp",
        Time:275,
},
    {
        id:6,
        Singer:"The Marías",
        Music:"Heavy",
        MusicPath:"The Marías - Heavy (Official Audio).mp3",
        ImagePath:"The Marías.jpg",
        Time:253,
},
]